import Link from "next/link";
import { Reveal, Stagger, StaggerItem } from "@/components/marketing/Motion";

const tracks = [
  { name: "Local evaluation", state: "Available now", body: "Run the recovery sandbox and Python sidecar locally.", items: ["Local durable event store", "Microsoft-shaped failure fixtures", "LangGraph adapter foundation", "Restart and one-time-link tests"], cta: "Open the lab", href: "/app" },
  { name: "Design partner", state: "3–5 teams", body: "Integrate one real delegated-auth workflow with direct founder support.", items: ["Real incident or recovery drill", "Vault and runtime adapter", "Shared success metrics", "Weekly architecture review"], cta: "Discuss a pilot", href: "mailto:founders@revive.dev?subject=Revive%20design%20partner" },
  { name: "Hosted control plane", state: "After validation", body: "Production service and commercial terms follow demonstrated demand.", items: ["Multi-tenant recovery cases", "Signed delivery webhooks", "Audit and policy history", "Operational support"], cta: "Join the waitlist", href: "mailto:founders@revive.dev?subject=Revive%20waitlist" },
];

export default function Pricing() {
  return <div className="mx-auto max-w-[1240px] px-5 py-20 sm:px-7 lg:py-28"><Reveal className="text-center"><div className="text-[9px] font-semibold uppercase tracking-[.14em] text-cobalt">Access</div><h1 className="mx-auto mt-5 max-w-[760px] text-[clamp(38px,6vw,64px)] font-semibold leading-[1] tracking-[-.055em] text-ink">Validate the recovery before inventing the pricing.</h1><p className="mx-auto mt-6 max-w-[650px] text-[14px] leading-6 text-ink-muted">Revive is a developer preview, not a finished self-serve SaaS. The current commercial path is a small number of serious design partners.</p></Reveal><Stagger className="mt-14 grid gap-4 lg:grid-cols-3">{tracks.map((track, index) => <StaggerItem key={track.name}><article className={`flex h-full flex-col rounded-[16px] border p-6 ${index === 1 ? "border-cobalt/25 bg-[#131720] text-white shadow-lift" : "border-hairline bg-white"}`}><div className={`text-[8px] font-semibold uppercase tracking-[.11em] ${index === 1 ? "text-[#92a2ff]" : "text-cobalt"}`}>{track.state}</div><h2 className={`mt-5 text-[20px] font-semibold tracking-[-.03em] ${index === 1 ? "text-white" : "text-ink"}`}>{track.name}</h2><p className={`mt-3 min-h-12 text-[11.5px] leading-5 ${index === 1 ? "text-white/45" : "text-ink-muted"}`}>{track.body}</p><ul className={`mt-7 space-y-3 border-t pt-6 ${index === 1 ? "border-white/10" : "border-hairline"}`}>{track.items.map((item) => <li key={item} className={`flex items-start gap-2.5 text-[10.5px] ${index === 1 ? "text-white/55" : "text-ink-muted"}`}><span className={index === 1 ? "text-[#8295ff]" : "text-ok"}>✓</span>{item}</li>)}</ul><Link href={track.href} className={`mt-8 inline-flex h-10 items-center justify-center rounded-[8px] text-[11px] font-semibold ${index === 1 ? "bg-white text-ink" : "border border-hairline bg-paper-base text-ink"}`}>{track.cta}</Link></article></StaggerItem>)}</Stagger><Reveal className="mt-16 border-t border-hairline pt-8 text-center text-[10.5px] leading-5 text-ink-faint">A paid pilot should be priced around the operational value of protected workflows—not arbitrary “recoveries per month.”</Reveal></div>;
}
