import { cookies } from "next/headers";
import { PageHeader, SectionHeading, SummaryStrip } from "@/components/app/ConsolePrimitives";
import { BillingControls } from "@/components/app/BillingControls";
import { getOrganizationBilling, organizationIdForWorkspace, PLAN_LIMITS } from "@/lib/billing";
import { SESSION_COOKIE, verifySession } from "@/lib/auth";
import { listSessions } from "@/lib/store";
import { selectedWorkspace, WORKSPACE_COOKIE } from "@/lib/workspaces";

export const dynamic = "force-dynamic";
export default async function UsagePage() { const jar = await cookies(); const auth = verifySession(jar.get(SESSION_COOKIE)?.value)!; const workspace = await selectedWorkspace(auth.email, jar.get(WORKSPACE_COOKIE)?.value); const billing = await getOrganizationBilling(workspace.id, await organizationIdForWorkspace(workspace.id)); const sessions = listSessions().filter((session) => !session.workspaceId || session.workspaceId === workspace.id); const steps = sessions.reduce((sum, session) => sum + session.revive.metrics.completedSteps, 0); const checkpoints = sessions.filter((session) => session.revive.checkpoint).length; const reauths = sessions.reduce((sum, session) => sum + session.revive.metrics.reconsents, 0); const actions = sessions.reduce((sum, session) => sum + session.revive.actions.length, 0); return <div className="mx-auto max-w-[1180px] px-4 pb-20 pt-7 sm:px-6 lg:px-8"><PageHeader eyebrow="Account" title="Usage" description="Observed local control-plane records for the active workspace. No extrapolated cost or savings claims." /><div className="mt-5"><SummaryStrip items={[{ label: "Recovery cases", value: String(sessions.length), detail: "persisted sessions" }, { label: "Completed steps", value: String(steps), detail: "protected lane only", tone: "ok" }, { label: "Checkpoints", value: String(checkpoints), detail: "saved after auth failure", tone: "cobalt" }, { label: "Action records", value: String(actions), detail: "prepared or committed" }]} /></div><section className="instrument-panel mt-5 overflow-hidden"><SectionHeading title="Plan" meta="billing" /><BillingControls plan={billing.plan} connectionLimit={PLAN_LIMITS[billing.plan].connections} /></section><section className="instrument-panel mt-5 overflow-hidden"><SectionHeading title="Meter definitions" /><Row label="Interactive reauthorizations" value={reauths} detail="Approved recovery links that rotated a credential lease." /><Row label="Recovery checkpoints" value={checkpoints} detail="Runs with a persisted step-accurate checkpoint." /><Row label="Completed protected steps" value={steps} detail="Successful steps in Revive-protected sandbox lanes." /></section></div>; }
function Row({ label, value, detail }: { label: string; value: number; detail: string }) { return <div className="grid gap-2 border-b border-[#e1e5ea] px-5 py-4 last:border-0 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="text-[10.5px] font-semibold">{label}</div><p className="mt-1 text-[9.5px] text-[#687180]">{detail}</p></div><span className="font-mono text-[16px] font-semibold text-[#2e49c8]">{value}</span></div>; }
