import { Reveal, Stagger, StaggerItem } from "@/components/marketing/Motion";

const implemented = [
  ["No token in checkpoints", "Durable checkpoints retain a fingerprint, scopes and execution cursor, not the raw credential."],
  ["One-time recovery capabilities", "Recovery URLs use 256 bits of entropy, expire after 15 minutes and are consumed atomically."],
  ["Credential generation fencing", "Reauthorization advances the lease generation so stale workers can be rejected."],
  ["Replay ambiguity guard", "Mutating actions stop instead of retrying blindly when the upstream outcome cannot be established."],
  ["OAuth transaction integrity", "Entra recovery uses S256 PKCE, encrypted HttpOnly transaction state, a short expiry and constant-time state comparison."],
  ["Encrypted credential records", "Token sets are sealed with AES-256-GCM before local or Postgres persistence."],
  ["Signed durable delivery", "Recovery webhooks carry timestamped HMAC signatures and retry through a Postgres queue with a terminal dead state."],
];
const gates = ["Owned-tenant Entra consent and callback verification", "Managed KMS rotation and secret-manager deployment", "Managed Postgres backups and continuously operated queue workers", "Tenant isolation, audit identity and role-based access", "External security assessment and compliance program"];

export default function Security() {
  return <div className="mx-auto max-w-[1100px] px-5 py-20 sm:px-7 lg:py-28"><Reveal><div className="text-[9px] font-semibold uppercase tracking-[.14em] text-cobalt">Security posture</div><h1 className="mt-5 max-w-[780px] text-[clamp(38px,6vw,64px)] font-semibold leading-[1] tracking-[-.055em] text-ink">Security claims should match the code that exists.</h1><p className="mt-6 max-w-[720px] text-[14px] leading-6 text-ink-muted">The current repository implements meaningful local safety primitives. It is not yet a certified hosted credential service, and the remaining production gates are explicit below.</p></Reveal><Stagger className="mt-14 grid gap-4 sm:grid-cols-2">{implemented.map(([title, body], index) => <StaggerItem key={title}><article className="h-full border border-hairline bg-white p-6"><div className="flex items-center justify-between"><span className="font-mono text-[9px] text-cobalt">0{index + 1}</span><span className="bg-ok-soft px-2 py-1 text-[8px] font-semibold uppercase tracking-[.08em] text-ok">implemented</span></div><h2 className="mt-8 text-[16px] font-semibold tracking-[-.025em] text-ink">{title}</h2><p className="mt-3 text-[11px] leading-5 text-ink-muted">{body}</p></article></StaggerItem>)}</Stagger><Reveal className="mt-16 overflow-hidden border border-cobalt bg-cobalt-soft text-ink"><div className="border-b border-cobalt/20 px-6 py-5"><div className="text-[9px] font-semibold uppercase tracking-[.12em] text-cobalt">Production gates</div><h2 className="mt-3 text-[22px] font-semibold tracking-[-.03em]">Required before handling customer credentials</h2></div><div className="divide-y divide-cobalt/15">{gates.map((gate, index) => <div key={gate} className="flex items-center gap-4 px-6 py-4"><span className="font-mono text-[8px] text-ink-faint">0{index + 1}</span><span className="text-[10.5px] text-ink-muted">{gate}</span><span className="ml-auto border border-cobalt/20 px-2 py-1 text-[7.5px] font-semibold uppercase tracking-[.08em] text-cobalt">open</span></div>)}</div></Reveal><Reveal className="mt-12 text-[10.5px] leading-5 text-ink-faint">For architecture or security review discussions: <a className="font-medium text-cobalt" href="mailto:security@revive.dev">security@revive.dev</a></Reveal></div>;
}
