import Link from "next/link";
import { HeroVisual } from "@/components/marketing/HeroVisual";
import { HeroDrift, Lift, Reveal, Stagger, StaggerItem } from "@/components/marketing/Motion";

const primitives = [
  { n: "01", title: "Run–credential binding", body: "Map a credential lease to every active run and the exact action it interrupted.", tag: "correlation" },
  { n: "02", title: "Durable recovery case", body: "Persist the checkpoint and recovery state so the original worker can disappear safely.", tag: "continuity" },
  { n: "03", title: "Fenced credential rotation", body: "Advance the lease generation so stale workers cannot reuse invalid credentials.", tag: "identity" },
  { n: "04", title: "Idempotent replay", body: "Resume with the original action key and stop when the upstream result is ambiguous.", tag: "safety" },
];

const integrations = [
  { name: "LangGraph", detail: "native interrupt + checkpoint adapter", status: "available" },
  { name: "Microsoft Entra", detail: "Authorization Code + PKCE adapter", status: "available" },
  { name: "Nango", detail: "connect-session and proxy adapter", status: "available" },
  { name: "Temporal", detail: "signal-based resume adapter", status: "available" },
];

export default function Home() {
  return <>
    <section className="relative overflow-hidden border-b border-hairline">
      <div className="marketing-grid absolute inset-0 -z-10 opacity-60" />
      <div className="absolute left-1/2 top-[-260px] -z-10 h-[620px] w-[760px] -translate-x-1/2 rounded-full bg-cobalt/[.08] blur-[100px]" />
      <div className="mx-auto grid min-h-[720px] max-w-[1240px] items-center gap-14 px-5 py-20 sm:px-7 lg:grid-cols-[1.02fr_.98fr] lg:py-24">
        <div>
          <Reveal y={14}><div className="inline-flex items-center gap-2 rounded-[7px] border border-hairline bg-white/80 px-3 py-1.5 shadow-seat backdrop-blur"><span className="h-1.5 w-1.5 rounded-full bg-cobalt" /><span className="text-[9px] font-semibold uppercase tracking-[.13em] text-ink-muted">Recovery control plane for durable agents</span></div></Reveal>
          <Reveal delay={.06}><h1 className="mt-6 max-w-[760px] text-balance text-[clamp(42px,6vw,72px)] font-semibold leading-[.98] tracking-[-.055em] text-ink">Credential failures shouldn&apos;t kill durable workflows.</h1></Reveal>
          <Reveal delay={.12}><p className="mt-6 max-w-[620px] text-[16px] leading-7 text-ink-muted">Revive binds an OAuth failure to the run it interrupted, gets the right account reauthorized, and resumes the failed action with its original idempotency key.</p></Reveal>
          <Reveal delay={.18} className="mt-8 flex flex-wrap gap-3"><Link href="/app" className="group inline-flex h-11 items-center gap-2 rounded-[9px] bg-ink px-5 text-[12.5px] font-semibold text-white shadow-sm transition hover:bg-[#292f3a]">Try the recovery lab <span className="transition-transform group-hover:translate-x-1">→</span></Link><Link href="#architecture" className="inline-flex h-11 items-center rounded-[9px] border border-hairline bg-white px-5 text-[12.5px] font-semibold text-ink transition hover:border-ink/20 hover:bg-paper-inset">See the architecture</Link></Reveal>
          <Reveal delay={.24} className="mt-8 grid max-w-[630px] grid-cols-2 gap-x-7 gap-y-4 border-t border-hairline pt-5 sm:grid-cols-4"><MiniStat value="256-bit" label="recovery links" /><MiniStat value="15 min" label="link lifetime" /><MiniStat value="durable" label="worker restart" /><MiniStat value="one key" label="action replay" /></Reveal>
        </div>
        <HeroDrift><HeroVisual /></HeroDrift>
      </div>
    </section>

    <section className="border-b border-hairline bg-white"><div className="mx-auto grid max-w-[1240px] divide-y divide-hairline px-5 sm:grid-cols-2 sm:divide-x sm:divide-y-0 sm:px-7 lg:grid-cols-4">{integrations.map((item) => <div key={item.name} className="flex items-center gap-3 px-0 py-4 sm:px-5 first:pl-0 last:pr-0"><span className={`h-1.5 w-1.5 shrink-0 rounded-full ${item.status === "available" ? "bg-ok" : "bg-ink-faint"}`} /><div className="min-w-0"><div className="flex items-center gap-2"><span className="text-[11px] font-semibold text-ink">{item.name}</span><span className="text-[7.5px] font-semibold uppercase tracking-[.09em] text-ink-faint">{item.status}</span></div><div className="mt-0.5 truncate text-[9.5px] text-ink-faint">{item.detail}</div></div></div>)}</div></section>

    <section id="product" className="mx-auto max-w-[1240px] px-5 py-24 sm:px-7 lg:py-32">
      <Reveal className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><Kicker>Product boundary</Kicker><h2 className="mt-4 max-w-[520px] text-[clamp(32px,4vw,48px)] font-semibold leading-[1.03] tracking-[-.045em] text-ink">The missing contract between identity and execution.</h2></div><p className="max-w-[610px] text-[14px] leading-6 text-ink-muted lg:justify-self-end">Credential systems know a grant is broken. Durable runtimes know how to pause a workflow. Neither system owns the correlation, recovery policy, identity handoff, and safe action replay between them.</p></Reveal>
      <div className="relative mt-14 grid gap-3 lg:grid-cols-[1fr_1.16fr_1fr]"><BoundaryCard label="Credential systems" title="Detect connection failure" items={["Refresh rejected", "Grant revoked", "Step-up required"]} muted /><div className="relative rounded-[16px] border border-cobalt/25 bg-[#131720] p-6 text-white shadow-[0_24px_60px_-32px_rgba(47,67,155,.6)]"><div className="flex items-center justify-between"><Kicker dark>Revive</Kicker><span className="rounded-[5px] bg-cobalt/20 px-2 py-1 text-[8px] font-semibold uppercase tracking-[.08em] text-[#9eacff]">control plane</span></div><h3 className="mt-5 text-[21px] font-semibold tracking-[-.025em]">Recover the logical run</h3><div className="mt-5 space-y-2.5">{["Bind credential → run → action", "Route authenticated reauthorization", "Rotate lease generation", "Resume with idempotency guard"].map((item, index) => <div key={item} className="flex items-center gap-3 rounded-[8px] border border-white/[.07] bg-white/[.035] px-3 py-2.5 text-[10.5px] text-white/65"><span className="font-mono text-[8px] text-[#8395ff]">0{index + 1}</span>{item}</div>)}</div></div><BoundaryCard label="Durable runtimes" title="Pause and resume execution" items={["Checkpoint state", "Wait for event", "Schedule retry"]} muted /></div>
    </section>

    <section id="architecture" className="border-y border-hairline bg-white"><div className="mx-auto max-w-[1240px] px-5 py-24 sm:px-7 lg:py-32"><Reveal><Kicker>Recovery architecture</Kicker><h2 className="mt-4 max-w-[700px] text-[clamp(32px,4vw,48px)] font-semibold leading-[1.04] tracking-[-.045em] text-ink">Six explicit state transitions. No magic token injection.</h2><p className="mt-5 max-w-[650px] text-[14px] leading-6 text-ink-muted">The worker can restart between every stage. The unit of continuity is the logical run and its checkpoint—not a process in memory.</p></Reveal><Stagger className="relative mt-14 grid gap-3 md:grid-cols-3 xl:grid-cols-6">{["Detect", "Bind", "Checkpoint", "Reauthorize", "Rotate", "Replay once"].map((step, index) => <StaggerItem key={step}><div className="group relative min-h-[150px] rounded-[13px] border border-hairline bg-paper-base p-4 transition hover:border-cobalt/25 hover:bg-white hover:shadow-lift"><div className="flex items-center justify-between"><span className="font-mono text-[9px] text-ink-faint">0{index + 1}</span><span className={`h-1.5 w-1.5 rounded-full ${index === 0 ? "bg-fail" : index === 5 ? "bg-ok" : "bg-cobalt"}`} /></div><div className="mt-8 text-[13px] font-semibold text-ink">{step}</div><p className="mt-2 text-[10.5px] leading-4 text-ink-faint">{architectureCopy[index]}</p>{index < 5 && <span className="absolute -right-[9px] top-1/2 z-10 hidden h-px w-[14px] bg-hairline xl:block" />}</div></StaggerItem>)}</Stagger></div></section>

    <section className="mx-auto max-w-[1240px] px-5 py-24 sm:px-7 lg:py-32"><Reveal className="text-center"><Kicker>Operational guarantees</Kicker><h2 className="mx-auto mt-4 max-w-[700px] text-[clamp(32px,4vw,48px)] font-semibold leading-[1.04] tracking-[-.045em] text-ink">Depth comes from invariants, not feature count.</h2></Reveal><Stagger className="mt-14 grid gap-4 md:grid-cols-2">{primitives.map((item) => <StaggerItem key={item.n}><Lift className="h-full"><article className="flex h-full min-h-[210px] flex-col rounded-[15px] border border-hairline bg-white p-6 shadow-seat"><div className="flex items-center justify-between"><span className="font-mono text-[9px] text-cobalt">{item.n}</span><span className="rounded-[5px] bg-paper-inset px-2 py-1 text-[8px] font-semibold uppercase tracking-[.09em] text-ink-faint">{item.tag}</span></div><h3 className="mt-10 text-[18px] font-semibold tracking-[-.025em] text-ink">{item.title}</h3><p className="mt-3 max-w-[520px] text-[12px] leading-5 text-ink-muted">{item.body}</p></article></Lift></StaggerItem>)}</Stagger></section>

    <section className="border-y border-hairline bg-[#10131a] text-white"><div className="mx-auto grid max-w-[1240px] gap-12 px-5 py-20 sm:px-7 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:py-24"><Reveal><Kicker dark>Company direction</Kicker><h2 className="mt-4 max-w-[560px] text-[clamp(30px,4vw,46px)] font-semibold leading-[1.04] tracking-[-.045em]">Recovery is the wedge. Run reliability is the platform.</h2><p className="mt-5 max-w-[590px] text-[13px] leading-6 text-white/45">The existing trace pipeline can eventually measure incident cost, retries, and action risk inside this control plane. It should not become a second product promise until customers pull Revive there.</p></Reveal><Stagger className="space-y-2">{[{label:"Now",title:"Credential failure recovery",status:"implemented foundation"},{label:"Next",title:"Vault and runtime integration matrix",status:"design partner work"},{label:"Later",title:"Run health, cost and policy intelligence",status:"earned expansion"}].map((item) => <StaggerItem key={item.label}><div className="flex items-center gap-4 rounded-[11px] border border-white/10 bg-white/[.035] p-4"><span className="w-10 text-[8px] font-semibold uppercase tracking-[.1em] text-[#8395ff]">{item.label}</span><div className="min-w-0 flex-1"><div className="text-[11px] font-medium text-white/75">{item.title}</div><div className="mt-0.5 text-[9px] text-white/30">{item.status}</div></div><span className="h-1.5 w-1.5 rounded-full bg-white/25" /></div></StaggerItem>)}</Stagger></div></section>

    <section id="faq" className="mx-auto max-w-[900px] px-5 py-24 sm:px-7 lg:py-32"><Reveal><Kicker>Questions</Kicker><h2 className="mt-4 text-[clamp(30px,4vw,44px)] font-semibold tracking-[-.045em] text-ink">The important distinctions.</h2></Reveal><Reveal delay={.08} className="mt-10 divide-y divide-hairline border-y border-hairline">{faqs.map((faq) => <details key={faq.q} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-[13px] font-semibold text-ink"><span>{faq.q}</span><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full border border-hairline text-[14px] font-normal text-ink-faint transition group-open:rotate-45 group-open:border-cobalt/20 group-open:text-cobalt">+</span></summary><p className="mt-3 max-w-[760px] pr-10 text-[12px] leading-5 text-ink-muted">{faq.a}</p></details>)}</Reveal></section>

    <section className="border-t border-hairline"><div className="mx-auto max-w-[1240px] px-5 py-20 sm:px-7"><Reveal className="relative overflow-hidden rounded-[18px] bg-cobalt p-8 text-white sm:p-12"><div className="marketing-grid-dark absolute inset-0 opacity-30" /><div className="relative flex flex-col gap-8 md:flex-row md:items-end md:justify-between"><div><div className="text-[9px] font-semibold uppercase tracking-[.13em] text-white/55">Developer preview</div><h2 className="mt-4 max-w-[650px] text-[clamp(30px,4vw,46px)] font-semibold leading-[1.03] tracking-[-.045em]">Break a credential. Watch the run survive.</h2><p className="mt-4 max-w-[560px] text-[12px] leading-5 text-white/65">The local recovery lab demonstrates checkpointing, one-time reauthorization, credential generations, and idempotent replay.</p></div><Link href="/app" className="group inline-flex h-11 shrink-0 items-center gap-2 rounded-[9px] bg-white px-5 text-[12px] font-semibold text-ink shadow-sm">Open recovery lab <span className="transition-transform group-hover:translate-x-1">→</span></Link></div></Reveal></div></section>
  </>;
}

function Kicker({ children, dark = false }: { children: React.ReactNode; dark?: boolean }) { return <div className={`text-[9px] font-semibold uppercase tracking-[.14em] ${dark ? "text-[#92a2ff]" : "text-cobalt"}`}>{children}</div>; }
function MiniStat({ value, label }: { value: string; label: string }) { return <div><div className="font-mono text-[11px] font-medium text-ink">{value}</div><div className="mt-1 text-[9px] text-ink-faint">{label}</div></div>; }
function BoundaryCard({ label, title, items, muted }: { label: string; title: string; items: string[]; muted?: boolean }) { return <div className={`rounded-[16px] border border-hairline p-6 ${muted ? "bg-white" : "bg-paper-base"}`}><Kicker>{label}</Kicker><h3 className="mt-5 text-[18px] font-semibold tracking-[-.025em] text-ink">{title}</h3><div className="mt-6 space-y-3">{items.map((item) => <div key={item} className="flex items-center gap-2.5 text-[10.5px] text-ink-muted"><span className="h-1.5 w-1.5 rounded-full bg-ink-faint" />{item}</div>)}</div></div>; }

const architectureCopy = ["Normalize the provider signal.", "Correlate lease, run and action.", "Persist the exact execution point.", "Route the correct account securely.", "Fence stale credential generations.", "Reconcile before side effects repeat."];
const faqs = [
  { q: "Is this another token vault?", a: "No. The target product integrates with vaults such as Nango or Auth0. Revive owns the run–credential correlation and recovery state around them." },
  { q: "Is this just workflow retry?", a: "No. A retry with the same rejected grant fails again, and blind replay can duplicate remote side effects. Revive changes the credential generation and preserves the action key." },
  { q: "Does the current demo use real Microsoft credentials?", a: "The default lab remains an offline provider-shaped fixture. When Entra and storage variables are configured, the same recovery ticket uses the real Authorization Code + PKCE callback." },
  { q: "What about agent efficiency tooling?", a: "The existing trace pipeline can later measure protected calls, incident cost, retry patterns and recovery outcomes. That is useful infrastructure, but it should not dilute the initial recovery wedge." },
];
