import Link from "next/link";
import { Reveal, Stagger, StaggerItem } from "@/components/marketing/Motion";

const layers = [
  { label: "Credential layer", title: "Nango · Auth0 · Scalekit", body: "Stores connections, refreshes tokens and opens reconnect flows.", owns: "connection state", leaves: "affected workflow runs" },
  { label: "Recovery control plane", title: "Revive", body: "Correlates the broken connection to runs, policies and side effects.", owns: "recovery state", leaves: "token storage + scheduling" },
  { label: "Execution layer", title: "LangGraph · Temporal · Restate", body: "Persists workflow state, waits for events and resumes execution.", owns: "run state", leaves: "identity recovery" },
];

export default function Compare() {
  return <div className="mx-auto max-w-[1240px] px-5 py-20 sm:px-7 lg:py-28">
    <Reveal><div className="text-[9px] font-semibold uppercase tracking-[.14em] text-cobalt">Product boundary</div><h1 className="mt-5 max-w-[820px] text-[clamp(38px,6vw,64px)] font-semibold leading-[1] tracking-[-.055em] text-ink">Revive connects systems that already do their own jobs well.</h1><p className="mt-6 max-w-[700px] text-[14px] leading-6 text-ink-muted">The credible claim is not “zero competitors.” Credential platforms and durable runtimes already solve their respective layers. Revive targets the recovery contract between them.</p></Reveal>
    <Stagger className="mt-14 grid gap-3 lg:grid-cols-3">{layers.map((layer, index) => <StaggerItem key={layer.label}><article className={`h-full rounded-[16px] border p-6 ${index === 1 ? "border-cobalt/25 bg-[#131720] text-white shadow-lift" : "border-hairline bg-white"}`}><div className={`text-[8.5px] font-semibold uppercase tracking-[.12em] ${index === 1 ? "text-[#92a2ff]" : "text-cobalt"}`}>{layer.label}</div><h2 className={`mt-5 text-[18px] font-semibold tracking-[-.03em] ${index === 1 ? "text-white" : "text-ink"}`}>{layer.title}</h2><p className={`mt-3 text-[11.5px] leading-5 ${index === 1 ? "text-white/45" : "text-ink-muted"}`}>{layer.body}</p><dl className={`mt-8 divide-y ${index === 1 ? "divide-white/10" : "divide-hairline"}`}><div className="flex items-center justify-between py-3 text-[9.5px]"><dt className={index === 1 ? "text-white/30" : "text-ink-faint"}>Owns</dt><dd className={index === 1 ? "text-white/70" : "text-ink"}>{layer.owns}</dd></div><div className="flex items-center justify-between py-3 text-[9.5px]"><dt className={index === 1 ? "text-white/30" : "text-ink-faint"}>Does not own</dt><dd className={index === 1 ? "text-white/70" : "text-ink"}>{layer.leaves}</dd></div></dl></article></StaggerItem>)}</Stagger>
    <Reveal className="mt-20"><div className="grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><div className="text-[9px] font-semibold uppercase tracking-[.14em] text-cobalt">Differentiation test</div><h2 className="mt-4 text-[32px] font-semibold leading-[1.05] tracking-[-.045em] text-ink">What Revive must prove.</h2><p className="mt-4 text-[12px] leading-5 text-ink-muted">These are engineering invariants and customer evidence—not a checklist of generic agent features.</p></div><div className="overflow-hidden rounded-[14px] border border-hairline bg-white">{[
      ["Cross-system correlation", "One credential event identifies every affected logical run and action."],
      ["Process-independent recovery", "A new worker resumes from durable state after the original process exits."],
      ["Safe side-effect handling", "Retries preserve idempotency and stop for reconciliation when outcome is ambiguous."],
      ["Vault and runtime neutrality", "Customers keep their credential system and workflow runtime."],
      ["Measured operational value", "Real incidents show recovery success, MTTR and zero duplicate effects."],
    ].map(([title, body], index) => <div key={title} className="grid gap-2 border-b border-hairline px-5 py-4 last:border-0 sm:grid-cols-[34px_1fr_1.4fr] sm:items-center"><span className="font-mono text-[9px] text-ink-faint">0{index + 1}</span><span className="text-[11px] font-semibold text-ink">{title}</span><span className="text-[10.5px] leading-4 text-ink-muted">{body}</span></div>)}</div></div></Reveal>
    <Reveal className="mt-20 rounded-[17px] border border-hairline bg-white p-7 sm:p-10"><div className="flex flex-col gap-7 md:flex-row md:items-end md:justify-between"><div><div className="text-[9px] font-semibold uppercase tracking-[.14em] text-cobalt">See the boundary in action</div><h2 className="mt-4 text-[30px] font-semibold tracking-[-.04em] text-ink">One failure. One recovery case. One logical run.</h2><p className="mt-3 max-w-[620px] text-[11.5px] leading-5 text-ink-muted">The sandbox exposes the checkpoint, provider signal, credential generation and action ledger directly.</p></div><Link href="/app" className="inline-flex h-10 shrink-0 items-center rounded-[8px] bg-ink px-4 text-[11px] font-semibold text-white">Open recovery lab →</Link></div></Reveal>
  </div>;
}
