import Link from "next/link";
import { Reveal, Stagger, StaggerItem } from "@/components/marketing/Motion";

const systems = [
  { title: "Workflow runtime", examples: "LangGraph, Temporal, Mastra", responsibility: "Persists agent state, reaches an interrupt and parks the current execution.", handoff: "Run ID, checkpoint and generation" },
  { title: "Revive Actions", examples: "User-action + continuation layer", responsibility: "Creates the customer-facing request, routes it, validates the response and resumes the exact run.", handoff: "Verified actor, structured response and signed continuation", active: true },
  { title: "Delivery and identity", examples: "Email, Slack, OAuth, SSO", responsibility: "Delivers the secure capability and performs provider or account authentication when required.", handoff: "Recipient delivery and identity evidence" },
];

const changes = [
  { event: "The agent lacks one required field", without: "It guesses, fails, or creates a generic support ticket detached from the run.", with: "Revive asks one focused question and returns the typed answer to the paused checkpoint." },
  { event: "A customer account loses access", without: "The run ends or engineering builds another provider-specific reconnect page.", with: "Revive reaches the account owner, binds restored access, and continues the same workflow." },
  { event: "A purchase exceeds policy", without: "An internal dashboard asks any available operator to click approve or reject.", with: "Revive routes the exact plan to the budget owner, who may approve, reject or modify it." },
  { event: "A browser needs OTP or passkey", without: "Automation stalls inside an ephemeral session and prior work is often repeated.", with: "Revive hands the secure browser step to the user and resumes from the saved generation." },
];

export default function Compare() {
  return <div className="bg-[#f4f5f1] text-[#151922]">
    <section className="border-b border-[#151922]"><div className="mx-auto max-w-[1240px] px-5 py-20 sm:px-8 lg:py-28"><Reveal><p className="text-[11px] font-semibold text-[#4967f2]">Why Revive</p><h1 className="mt-5 max-w-[940px] text-[clamp(42px,6vw,72px)] font-semibold leading-[.94] tracking-[-.065em]">Pausing an agent is easy. Getting the right human action back into the right run is not.</h1><p className="mt-7 max-w-[740px] text-[15px] leading-7 text-[#5f6876]">Revive owns the interaction between autonomous agents and the customers, owners, managers and administrators they depend on.</p></Reveal></div></section>
    <section className="mx-auto max-w-[1240px] px-5 py-20 sm:px-8 lg:py-28"><Reveal><h2 className="max-w-[760px] text-[36px] font-semibold leading-[1] tracking-[-.05em]">One human dependency across three systems.</h2></Reveal><Stagger className="mt-10 grid border border-[#151922] bg-[#fbfcf8] lg:grid-cols-3">{systems.map((system) => <StaggerItem key={system.title}><article className={`h-full border-b border-[#c8cdd2] p-6 last:border-b-0 lg:border-b-0 lg:border-r lg:last:border-r-0 ${system.active ? "bg-[#edf0ff]" : ""}`}><div className={`text-[12px] font-semibold ${system.active ? "text-[#2e49c8]" : "text-[#151922]"}`}>{system.title}</div><div className="mt-2 font-mono text-[8.5px] text-[#7b8491]">{system.examples}</div><p className="mt-7 text-[12px] leading-6 text-[#596273]">{system.responsibility}</p><div className="mt-8 border-t border-[#d7dce2] pt-4"><div className="font-mono text-[8px] tracking-[.08em] text-[#8a929d]">HANDOFF</div><div className="mt-2 text-[10.5px] font-medium leading-5 text-[#303640]">{system.handoff}</div></div></article></StaggerItem>)}</Stagger></section>
    <section className="border-y border-[#151922] bg-[#eef0eb]"><div className="mx-auto max-w-[1240px] px-5 py-20 sm:px-8 lg:py-28"><Reveal><h2 className="max-w-[760px] text-[36px] font-semibold leading-[1] tracking-[-.05em]">What changes at a real blocker.</h2><p className="mt-4 max-w-[620px] text-[13px] leading-6 text-[#687180]">The difference appears where agents currently guess, terminate or leave a human task disconnected from execution.</p></Reveal><div className="mt-10 border-t border-[#151922]">{changes.map((change) => <Reveal key={change.event} className="grid gap-5 border-b border-[#c8cdd2] py-7 lg:grid-cols-[.72fr_1fr_1fr]"><h3 className="text-[14px] font-semibold tracking-[-.02em]">{change.event}</h3><div><div className="text-[9px] font-semibold text-[#9a5c15]">Without a user-action layer</div><p className="mt-2 text-[11px] leading-5 text-[#687180]">{change.without}</p></div><div className="border-l-[3px] border-[#4967f2] pl-4"><div className="text-[9px] font-semibold text-[#2e49c8]">With Revive</div><p className="mt-2 text-[11px] leading-5 text-[#4f5866]">{change.with}</p></div></Reveal>)}</div></div></section>
    <section className="mx-auto max-w-[1240px] px-5 py-20 sm:px-8 lg:py-28"><Reveal className="grid gap-8 border border-[#151922] bg-[#fbfcf8] p-7 sm:p-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><h2 className="max-w-[720px] text-[34px] font-semibold leading-[1] tracking-[-.045em]">Complete one secure request end to end.</h2><p className="mt-4 max-w-[620px] text-[12px] leading-6 text-[#687180]">See the recipient, run, checkpoint, generation, structured response and continuation status in one record.</p></div><Link href="/app/requests" className="inline-flex h-11 w-fit items-center border border-[#151922] bg-[#151922] px-5 text-[11px] font-semibold text-white active:translate-y-px">Open action requests</Link></Reveal></section>
  </div>;
}
