"use client";

import { Check, Copy, Heartbeat, X } from "@phosphor-icons/react";
import { useRouter } from "next/navigation";
import { useState } from "react";

export function DeadRunResolveButton({ id, actionType, recipientRole }: { id: string; actionType: string; recipientRole: string }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [url, setUrl] = useState(""); const [copied, setCopied] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(""); const data = new FormData(event.currentTarget);
    const email = String(data.get("email") || "");
    const response = await fetch(`/api/workspaces/dead-runs/${encodeURIComponent(id)}/revive`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ recipient: { email, subjectId: String(data.get("subjectId") || "").trim() || email, role: recipientRole }, destinationUrl: String(data.get("destinationUrl") || "").trim() || undefined }) });
    const body = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setError(body.error || "Could not create resolution link."); return; } setUrl(body.request.url || ""); router.refresh();
  }
  async function copy() { await navigator.clipboard.writeText(url.startsWith("http") ? url : `${window.location.origin}${url}`); setCopied(true); window.setTimeout(() => setCopied(false), 1400); }
  return <><button onClick={() => setOpen(true)} className="inline-flex h-8 items-center gap-1.5 border border-[#4967f2] bg-[#edf0ff] px-3 text-[9px] font-semibold text-[#2e49c8] transition hover:bg-[#dfe3ff]"><Heartbeat size={11} />Revive</button>{open && <div className="fixed inset-0 z-[80] bg-[#151922]/25 backdrop-blur-[2px]" onMouseDown={() => setOpen(false)}><aside role="dialog" aria-modal="true" aria-label="Revive dead run" onMouseDown={(event) => event.stopPropagation()} className="ml-auto flex h-full w-full max-w-[440px] flex-col border-l border-[#151922] bg-[#f4f5f1]"><div className="flex items-center justify-between border-b border-[#151922] px-5 py-4"><div><h2 className="text-[15px] font-semibold">Resolve this run</h2><p className="mt-1 text-[9.5px] text-[#687180]">{actionType.replaceAll("_", " ")} · send to {recipientRole}</p></div><button aria-label="Close" onClick={() => setOpen(false)} className="flex h-8 w-8 items-center justify-center border border-[#c7ccd2]"><X size={13} /></button></div><form onSubmit={submit} className="flex flex-1 flex-col"><div className="flex-1 space-y-4 p-5"><label className="block"><span className="mb-1.5 block text-[9.5px] font-semibold text-[#596273]">Recipient email</span><input name="email" type="email" required className="console-input" placeholder="owner@customer.com" /></label><label className="block"><span className="mb-1.5 block text-[9.5px] font-semibold text-[#596273]">Recipient subject ID</span><input name="subjectId" className="console-input" placeholder="customer_account_owner" /></label>{actionType === "reauthorization" && <label className="block"><span className="mb-1.5 block text-[9.5px] font-semibold text-[#596273]">Reconnect URL</span><input name="destinationUrl" type="url" className="console-input" placeholder="https://connect.example.com/..." /></label>}{error && <p className="border-l-[3px] border-[#af4039] bg-[#fff0ee] px-3 py-2 text-[10px] text-[#8f342f]">{error}</p>}{url && <div className="border border-[#18724e] bg-[#edf8f2] p-4"><div className="text-[10px] font-semibold text-[#18724e]">Resolution link created</div><button type="button" onClick={() => void copy()} className="mt-3 inline-flex h-8 items-center gap-1.5 border border-[#18724e] px-3 text-[9px] font-semibold text-[#18724e]">{copied ? <Check size={11} /> : <Copy size={11} />}{copied ? "Copied" : "Copy link"}</button></div>}</div><div className="border-t border-[#151922] bg-[#fbfcf8] p-5"><button disabled={busy} className="h-10 w-full bg-[#4967f2] text-[10.5px] font-semibold text-white disabled:opacity-50">{busy ? "Creating…" : "Create secure action"}</button></div></form></aside></div>}</>;
}
