import Link from "next/link";
import { cookies } from "next/headers";
import { ArrowRight, Pulse } from "@phosphor-icons/react/dist/ssr";
import { SESSION_COOKIE, verifySession } from "@/lib/auth";
import { selectedWorkspace, WORKSPACE_COOKIE } from "@/lib/workspaces";
import { getDeadRunStats, listDeadRuns } from "@/lib/dead-runs";
import { PageHeader, SummaryStrip, ago, StatusBadge } from "@/components/app/ConsolePrimitives";
import { DeadRunAnalyzer } from "@/components/app/DeadRunAnalyzer";
import { DeadRunResolveButton } from "@/components/app/DeadRunResolveButton";
import { workspaceRole } from "@/lib/rbac";

export const dynamic = "force-dynamic";

export default async function DetectorPage() {
  const jar = await cookies(); const auth = verifySession(jar.get(SESSION_COOKIE)?.value)!; const workspace = await selectedWorkspace(auth.email, jar.get(WORKSPACE_COOKIE)?.value);
  const [stats, runs, role] = await Promise.all([getDeadRunStats(workspace.id, 7).catch(() => ({ days: 7, totalRunsLost: 0, recoverableRuns: 0, recoverableRate: 0, wastedTokens: 0, estimatedCostUsd: 0, resolvedRuns: 0, categories: [] })), listDeadRuns(workspace.id).catch(() => []), workspaceRole(auth.email, workspace)]);
  const canResolve = role === "operator" || role === "admin" || role === "owner";
  return <div className="mx-auto max-w-[1180px] px-4 pb-20 pt-7 sm:px-6 lg:px-8">
    <PageHeader eyebrow="Free detector" title="Runs you paid for and lost" description="See which agent runs died at human-dependent blockers, what they cost, and which person could have saved them." actions={<Link href="/app/quickstart" className="inline-flex h-9 items-center gap-2 border border-[#151922] bg-[#151922] px-4 text-[10.5px] font-semibold text-white">Install detector <ArrowRight size={11} /></Link>} />
    <div className="mt-5"><SummaryStrip items={[{ label: "Runs lost · 7d", value: String(stats.totalRunsLost), detail: "terminal failures observed", tone: stats.totalRunsLost ? "warn" : undefined }, { label: "Human-recoverable", value: stats.totalRunsLost ? `${Math.round(stats.recoverableRate * 100)}%` : "—", detail: `${stats.recoverableRuns} runs could be revived`, tone: stats.recoverableRuns ? "cobalt" : undefined }, { label: "Wasted tokens", value: stats.wastedTokens.toLocaleString(), detail: "reported by runtime" }, { label: "Estimated cost", value: stats.estimatedCostUsd ? `$${stats.estimatedCostUsd.toFixed(2)}` : "—", detail: stats.estimatedCostUsd ? "reported model cost" : "send cost metadata" }]} /></div>
    {stats.categories.length > 0 && <section className="instrument-panel mt-5 p-5"><div className="font-mono text-[8px] tracking-[.1em] text-[#7b8491]">WHY RUNS DIED</div><div className="mt-4 flex h-3 overflow-hidden bg-[#e2e5df]">{stats.categories.map((item, index) => <span key={item.category} title={`${item.category}: ${Math.round(item.share * 100)}%`} className={index === 0 ? "bg-[#4967f2]" : index === 1 ? "bg-[#7d8fe8]" : index === 2 ? "bg-[#aab4e8]" : "bg-[#c8cdd7]"} style={{ width: `${Math.max(2, item.share * 100)}%` }} />)}</div><div className="mt-4 flex flex-wrap gap-x-6 gap-y-2">{stats.categories.map((item) => <span key={item.category} className="font-mono text-[8.5px] text-[#596273]">{item.category.replaceAll("_", " ")} <strong className="text-[#151922]">{Math.round(item.share * 100)}%</strong></span>)}</div></section>}
    <div className="mt-5"><DeadRunAnalyzer /></div>
    <section className="instrument-panel mt-5 overflow-hidden"><div className="flex items-center justify-between border-b border-[#151922] px-5 py-4"><div><h2 className="text-[12px] font-semibold">Observed dead runs</h2><p className="mt-1 text-[9.5px] text-[#687180]">Detector records only redacted excerpt, classification and cost metadata.</p></div><span className="font-mono text-[8.5px] text-[#7b8491]">{runs.length} TOTAL</span></div>{runs.length ? runs.slice(0, 100).map((run) => <div key={run.id} className="grid gap-3 border-b border-[#e1e4de] px-5 py-4 last:border-b-0 sm:grid-cols-[minmax(0,1fr)_130px_100px_auto] sm:items-center"><div className="min-w-0"><div className="truncate text-[11px] font-semibold">{run.runId}</div><div className="mt-1 truncate font-mono text-[8.5px] text-[#8a929d]">{run.runtime} · {run.failureMessage}</div></div><span className="font-mono text-[8.5px] text-[#596273]">{run.category.replaceAll("_", " ")}</span><StatusBadge tone={run.status === "resolved" ? "ok" : run.status === "resolution_requested" ? "cobalt" : run.recoverable ? "warn" : "neutral"}>{run.status.replaceAll("_", " ")}</StatusBadge><div className="flex items-center justify-end gap-3"><span className="font-mono text-[8px] text-[#8a929d]">{ago(run.createdAt)}</span>{canResolve && run.recoverable && run.status === "detected" && <DeadRunResolveButton id={run.id} actionType={run.suggestedActionType} recipientRole={run.suggestedRecipientRole} />}{run.actionRequestId && <Link href={`/app/requests/${run.actionRequestId}`} className="text-[9px] font-semibold text-[#2e49c8]">Open</Link>}</div></div>) : <div className="px-5 py-10"><Pulse size={24} className="text-[#4967f2]" /><h3 className="mt-4 text-[15px] font-semibold">No run failures observed</h3><p className="mt-2 max-w-[500px] text-[10.5px] leading-5 text-[#687180]">Install one interrupt adapter. Detector starts showing blocker mix and loss without asking any end user to respond.</p></div>}</section>
  </div>;
}
