import { CODE_TABLE } from "@/lib/graph-codes";
import { PageHeader, StatusBadge } from "@/components/app/ConsolePrimitives";

const CONNECTIONS = [
  { name: "Microsoft Entra", group: "Credential systems", role: "Identity provider", detail: "Authorization Code + PKCE with account binding", last: "sandbox active", mark: "M", color: "#0b76ce" },
  { name: "Nango", group: "Credential systems", role: "Credential vault", detail: "Scoped connect sessions and authenticated proxy", last: "not configured", mark: "N", color: "#25282e" },
  { name: "Auth0 Token Vault", group: "Credential systems", role: "Credential vault", detail: "Backend federated token exchange", last: "not configured", mark: "A", color: "#e45d3f" },
  { name: "LangGraph", group: "Durable runtimes", role: "Runtime adapter", detail: "Native interrupt and checkpoint handoff", last: "adapter tested", mark: "L", color: "#24745b" },
  { name: "Temporal", group: "Durable runtimes", role: "Runtime adapter", detail: "Signal workflows with opaque lease references", last: "adapter tested", mark: "T", color: "#625be7" },
  { name: "Signed webhooks", group: "Delivery", role: "Event delivery", detail: "HMAC signatures, retries and terminal dead state", last: "queue idle", mark: "W", color: "#775c3e" },
];

export default function ConnectionsPage() {
  return <div className="mx-auto max-w-[1400px] px-4 pb-20 pt-7 sm:px-6 lg:px-8">
    <PageHeader eyebrow="Integration surface" title="Connections" description="Credential systems own tokens. Durable runtimes own execution. Revive owns the recovery evidence between them." actions={<StatusBadge tone="ok"><span className="h-1.5 w-1.5 rounded-full bg-current" />6 adapters</StatusBadge>} />

    <div className="mt-5 grid gap-5 xl:grid-cols-[1.25fr_.75fr]">
      <section className="instrument-panel overflow-hidden rounded-[8px]">
        {['Credential systems', 'Durable runtimes', 'Delivery'].map((group) => <div key={group} className="border-b border-[#e2e3df] last:border-0"><div className="bg-[#eef0eb] px-4 py-2 font-mono text-[8px] tracking-[.12em] text-[#737c89]">{group.toUpperCase()}</div>{CONNECTIONS.filter((item) => item.group === group).map((item) => <div key={item.name} className="group grid gap-3 border-t border-[#e9eae5] px-4 py-4 transition hover:bg-[#fafaf6] sm:grid-cols-[1.1fr_1.35fr_.7fr_auto] sm:items-center"><div className="flex min-w-0 items-center gap-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-[6px] text-[10px] font-semibold text-white" style={{ background: item.color }}>{item.mark}</span><div className="min-w-0"><div className="truncate text-[11px] font-semibold text-[#2a2d32]">{item.name}</div><div className="mt-0.5 text-[8px] uppercase tracking-[.09em] text-[#95989d]">{item.role}</div></div></div><p className="text-[9.5px] leading-4 text-[#686d74]">{item.detail}</p><span className="font-mono text-[8.5px] text-[#92959a]">{item.last}</span><StatusBadge tone="ok">available</StatusBadge></div>)}</div>)}
      </section>

      <aside className="recorder-panel overflow-hidden border border-[#151922] text-[#151922]"><div className="border-b border-[#151922] px-5 py-4"><div className="font-mono text-[8px] tracking-[.11em] text-[#2e49c8]">SYSTEM BOUNDARY</div><h2 className="mt-2 text-[16px] font-semibold tracking-[-.025em]">One recovery contract</h2></div><div className="p-5"><Boundary title="Credential system" body="Detects a broken grant and issues replacement credentials." /><Boundary title="Revive continuity layer" body="Correlates connection, run, checkpoint, policy and action key." active /><Boundary title="Durable runtime" body="Persists workflow state and resumes the existing execution." /><div className="mt-5 border-t border-[#bcc4cf] pt-4 font-mono text-[8.5px] leading-5 text-[#687180]">RAW TOKEN: excluded<br/>WORKFLOW HISTORY: opaque lease + generation<br/>REPLAY MODE: reconcile before repeat</div></div></aside>
    </div>

    <section className="instrument-panel mt-5 overflow-hidden rounded-[8px]"><div className="flex flex-col gap-2 border-b border-[#e2e3df] px-5 py-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-[12px] font-semibold text-[#2a2d32]">Recovery policy catalog</h2><p className="mt-1 text-[9.5px] text-[#777b81]">Provider signals select a fail-safe path. Unknown errors escalate instead of retrying blindly.</p></div><span className="font-mono text-[8.5px] text-[#92959a]">{CODE_TABLE.length} sourced policies · v0.2</span></div><div className="hidden grid-cols-[.75fr_.9fr_.7fr_1.45fr_.45fr] gap-4 border-b border-[#e5e6e2] bg-[#f3f3ee] px-5 py-2.5 text-[8px] font-semibold uppercase tracking-[.1em] text-[#909398] md:grid"><span>Provider</span><span>Signal</span><span>Decision</span><span>Recovery policy</span><span>Source</span></div>{CODE_TABLE.map((policy) => <div key={`${policy.provider}-${policy.code}`} className="grid gap-2 border-b border-[#e9eae5] px-5 py-3.5 last:border-0 md:grid-cols-[.75fr_.9fr_.7fr_1.45fr_.45fr] md:items-center md:gap-4"><span className="text-[9.5px] font-medium capitalize text-[#383c42]">{policy.provider}</span><span className="font-mono text-[8.5px] text-[#656970]">{policy.code}</span><StatusBadge tone={policy.verdict === "dead" ? "fail" : policy.verdict === "transient" ? "warn" : "ok"}>{policy.verdict}</StatusBadge><div><div className="text-[9.5px] font-medium text-[#303339]">{policy.title}</div><div className="mt-0.5 text-[8.5px] text-[#92959a]">{policy.remediation}</div></div><a href={policy.source} target="_blank" rel="noreferrer" className="text-[9px] font-medium text-[#5065e8] hover:underline">Docs ↗</a></div>)}</section>
  </div>;
}

function Boundary({ title, body, active = false }: { title: string; body: string; active?: boolean }) { return <div className={`relative mb-2 border-l-[3px] px-4 py-3 ${active ? "border-[#4967f2] bg-[#fbfcf8]" : "border-[#b7bec8]"}`}><div className={`text-[10.5px] font-semibold ${active ? "text-[#2e49c8]" : "text-[#3f4753]"}`}>{title}</div><p className="mt-1 text-[9px] leading-4 text-[#687180]">{body}</p></div>; }
